=== hubmapconsortium/portal-ui/context/app/static/js/components/detailPage/provenance/ProvVis/prov-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/hubmapconsortium/prov-vis/#schema",
  "title": "HuBMAP PROV schema",
  "type": "object",
  "definitions": {
    "string_to_anything": {
      "type": "object",
      "patternProperties": {
        ".": {
          "$comment": "Usually string, but boolean or object in some cases."
        }
      }
    },
    "string_to_string_to_anything": {
      "type": "object",
      "patternProperties": {
        ".": {
          "$ref": "#/definitions/string_to_anything"
        }
      }
    }
  },
  "additionalProperties": false,
  "required": ["prefix", "entity", "activity", "wasGeneratedBy", "used"],
  "properties": {
    "prefix": { "$ref": "#/definitions/string_to_anything" },
    "entity": { "$ref": "#/definitions/string_to_string_to_anything" },
    "activity": { "$ref": "#/definitions/string_to_string_to_anything" },
    "wasGeneratedBy": { "$ref": "#/definitions/string_to_string_to_anything" },
    "wasStartedBy": { "$ref": "#/definitions/string_to_string_to_anything" },
    "wasAssociatedWith": { "$ref": "#/definitions/string_to_string_to_anything" },
    "mentionOf": { "$ref": "#/definitions/string_to_string_to_anything" },
    "hadMember": { "$ref": "#/definitions/string_to_string_to_anything" },
    "wasEndedBy": { "$ref": "#/definitions/string_to_string_to_anything" },
    "specializationOf": { "$ref": "#/definitions/string_to_string_to_anything" },
    "used": { "$ref": "#/definitions/string_to_string_to_anything" },
    "agent": { "$ref": "#/definitions/string_to_string_to_anything" },
    "bundle": { "$ref": "#/definitions/string_to_string_to_anything" },
    "actedOnBehalfOf": { "$ref": "#/definitions/string_to_string_to_anything" }
  }
}

=== hubmapconsortium/portal-ui/context/app/static/js/components/detailPage/provenance/ProvVis/__tests__/fixtures/simple-prov.json
{
  "prefix": {
    "ex": "http://example.com#",
    "prov": "http://www.w3.org/ns/prov#"
  },
  "entity": {
    "ex:input": {
      "prov:label": "Input",
      "ex:note": "Begins here..."
    },
    "ex:output": {
      "prov:label": "Output",
      "ex:note": "... and ends here."
    }
  },
  "activity": {
    "ex:process": {
      "prov:label": "Process"
    }
  },
  "wasGeneratedBy": {
    "_:1": {
      "prov:activity": "ex:process",
      "prov:entity": "ex:output"
    }
  },
  "used": {
    "_:2": {
      "prov:activity": "ex:process",
      "prov:entity": "ex:input"
    }
  },
  "agent": {
    "ex:j-austen": {
      "ex:DisplayName": "Jane Austen",
      "prov:type": "prov:Person"
    },
    "ex:example-com": {
      "ex:DisplayName": "Example.com, incorporated",
      "prov:type": "prov:Organization"
    }
  },
  "actedOnBehalfOf": {
    "_:id6": {
      "prov:delegate": "ex:j-austen",
      "prov:responsible": "ex:example-com",
      "prov:activity": "ex:process"
    }
  }
}

=== hubmapconsortium/portal-ui/context/app/static/js/components/detailPage/provenance/ProvVis/__tests__/fixtures/complex-prov.json
{
  "prefix": {
    "hubmap": "https://hubmapconsortium.org/",
    "prov": "http://www.w3.org/ns/prov#"
  },
  "entity": {
    "hubmap:ent-1": { "prov:label": "ent-1" },
    "hubmap:ent-2": { "prov:label": "ent-2" },
    "hubmap:ent-3": { "prov:label": "ent-3" },
    "hubmap:ent-4": { "prov:label": "ent-4" },
    "hubmap:ent-5": { "prov:label": "ent-5" },
    "hubmap:ent-6": { "prov:label": "ent-6" },
    "hubmap:ent-7": { "prov:label": "ent-7" }
  },
  "activity": {
    "hubmap:act-1": { "prov:label": "act-1" },
    "hubmap:act-2": { "prov:label": "act-2" },
    "hubmap:act-3": { "prov:label": "act-3" },
    "hubmap:act-4": { "prov:label": "act-4" }
  },
  "wasGeneratedBy": {
    "_:1": { "prov:entity": "hubmap:ent-3", "prov:activity": "hubmap:act-1" },
    "_:2": { "prov:entity": "hubmap:ent-4", "prov:activity": "hubmap:act-2" },
    "_:3": { "prov:entity": "hubmap:ent-5", "prov:activity": "hubmap:act-3" },
    "_:4": { "prov:entity": "hubmap:ent-6", "prov:activity": "hubmap:act-4" },
    "_:5": { "prov:entity": "hubmap:ent-7", "prov:activity": "hubmap:act-2" }
  },
  "used": {
    "_:5": { "prov:activity": "hubmap:act-1", "prov:entity": "hubmap:ent-1" },

    "_:6": { "prov:activity": "hubmap:act-2", "prov:entity": "hubmap:ent-1" },
    "_:7": { "prov:activity": "hubmap:act-2", "prov:entity": "hubmap:ent-2" },

    "_:8": { "prov:activity": "hubmap:act-3", "prov:entity": "hubmap:ent-3" },

    "_:9": { "prov:activity": "hubmap:act-4", "prov:entity": "hubmap:ent-1" },
    "_:10": { "prov:activity": "hubmap:act-4", "prov:entity": "hubmap:ent-3" },
    "_:11": { "prov:activity": "hubmap:act-4", "prov:entity": "hubmap:ent-4" }
  }
}
